### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by trarbr** [trarbr/csgo_stats#29]
Now that we have equipment events soon (🤞), it would be really nice with icons. I found that the official icons can be extracted from the game files, and now have them sitting as PNG and SVG in a directory. But, can we use them? According to this [official page](https://store.steampowered.com/video_policy), that seems to be a no.

Or is there some loophole somewhere? [This community thread](https://steamcommunity.com/app/1840/discussions/0/620695877119311119/) gave me hope, but I don't think it covers our situation, especially not after reading the official page.

Any other sources of icons?

**Comment by nicoeg** [comment]
As long as we do not intend to make money on this, then I don't Valve will come after us for using the icons 😃
